"""
Django settings for kanban project.

Generated by 'django-admin startproject' using Django 3.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# Set the secure flag for cookies to ensure they are transmitted over HTTPS only
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
# Redirect all HTTP requests to HTTPS
SECURE_SSL_REDIRECT = True
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'k2x$pdi069z=^g0le=hs)$v4fbkid*h$tk@djv$j_!=3^^1!k$'

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True


# # SSL/TLS Configuration
# SSL_DIR = os.path.join(BASE_DIR, 'certificates')
# CERTIFICATE_FILE = os.path.join(SSL_DIR, 'localhost.crt')
# PRIVATE_KEY_FILE = os.path.join(SSL_DIR, 'localhost.decrypted.key')

# # If you are using a local development server, you may need to disable the HTTPS redirect
# if DEBUG:
#     SSL_DIR = os.path.join(BASE_DIR, 'certidicates')
#     CERTIFICATE_FILE = os.path.join(SSL_DIR, 'localhost.crt')
#     PRIVATE_KEY_FILE = os.path.join(SSL_DIR, 'localhost.key')

#     if os.path.exists(CERTIFICATE_FILE) and os.path.exists(PRIVATE_KEY_FILE):
#         SECURE_SSL_REDIRECT = True
#         SECURE_SSL_HOST = 'localhost'
#         SECURE_SSL_PORT = 8443
#         SECURE_SSL_REDIRECT_EXEMPT = [r'^health_check/$']  # URLs to exclude from HTTPS redirect
#         SECURE_HSTS_SECONDS = 31536000  # 1 year in seconds (optional)
#         SECURE_HSTS_INCLUDE_SUBDOMAINS = True  # (optional)
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'kanban_api',
    'sslserver',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'kanban.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kanban.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
'default': {
'ENGINE': 'django.db.backends.mysql',
# 'NAME': os.environ.get('MYSQL_DATABASE'),
# 'USER': os.environ.get('MYSQL_USER'),
# 'PASSWORD': os.environ.get('MYSQL_PASSWORD'),
'NAME' : 'kanban',
'USER' : 'root',
'PASSWORD' : 'Root@123',
'HOST': 'localhost', # typically 'localhost' or '127.0.0.1'
'PORT': '3306', # default MySQL port is usually 3306
}
}

#   export FLYCTL_INSTALL="/home/sanskarjaiswal/.fly"
#   export PATH="$FLYCTL_INSTALL/bin:$PATH"
# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

ALLOWED_HOSTS = ["*"]

CORS_ALLOWED_ORIGINS = [
"http://localhost:5173",
"http://127.0.0.1:5174",
"https://127.0.0.1:5174",
"https://localhost:5174",
"http://localhost:5174",
]
CORS_ALLOW_METHODS = [
'DELETE',
'GET',
'OPTIONS',
'POST',
'PUT',
]